### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000001",
  "amount": 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000001",
  "amount": 200
}


### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "08346397f18a4f2590695df17a15b5a6",
  "accountNumber": "1000000001",
  "amount": 20000
}

### query transaction
GET http://localhost:8080/transaction/548eb0cd5eee4968a3742ede792a6e5f

